version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: parts_db
      POSTGRES_USER: sofia
      POSTGRES_PASSWORD: sofia123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
